version: "3.9"
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - HOST=0.0.0.0
    command: npm start

  backend:
    build: ../BotXPert-Backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ../BotXPert-Backend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000
